---
# ----------------------------------------------------------------------------------------
- name: Dell Ubuntu lappi
  hosts: dell-ubuntu
  become: true
  vars_files:
    - 'vars/vault.yml'
    - 'group_vars/{{ ansible_os_family }}.yml'
  roles:
    - role: base
    - role: apt
    - role: workstation
    - role: petermosmans.customize-gnome
      tags: gnome
    - role: geerlingguy.nfs
    - role: generate-fstab
    - role: geerlingguy.docker
    - role: "diademiemi.flatpak"
      tags: flatpak
    - role: gikeymarcia.neovim
      tags: nvim
    - role: intel-iGPU-driver
      tags: gpu