- name: Setup cron jobs
  cron:
    user: "{{ item.user }}"
    job: "{{ item.job }} {% if (item.healthcheck_io_uuid | default('') | length) > 0 %}&& curl -fsS -m 10 --retry 5 -o /dev/null {{ healthcheck_io_host }}/{{ item.healthcheck_io_uuid }} > /dev/null{% endif %}"
    name: "{{ item.name }}"
    weekday: "{{ item.weekday | default ('*') }}"
    minute: "{{ item.minute | default ('00')}}"
    hour: "{{ item.hour | default ('00') }}"
    dom: "{{ item.dom|default('*') }}"
  with_items: '{{ cron }}'

- name: Setup startup cron jobs
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    job: "{{item.job}}"
    special_time: reboot
  with_items: '{{ cron_reboot }}'
  when: cron_reboot is defined
 
