# m4rcu5nl/ansible-role-zerotier
hostname: oraclevmpublic
main_username: ubuntu
main_groupname: "{{main_username}}"
main_uid: "1000"
main_gid: "{{main_uid}}"

# grog.package
package_update_cache: yes
package_list:
  - name: bash-completion
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python3
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: mergerfs
  - name: snapper
  - name: sudo
  - name: apparmor
  - name: restic
  - name: neovim
#geerlingguy.docker
docker_edition: 'ce'
docker_install_compose: true
docker_data_dir: /docker/config






tailscale_args: "--accept-dns=false --hostname={{hostname}} --accept-routes --reset"
