---
hostname: proxy
package_update_cache: yes
package_list:
  - name: bash-completion
  - name: curl
  - name: git
  - name: htop
  - name: iftop
  - name: iotop
  - name: lm-sensors
  - name: mc
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: openssh-server
  - name: python3
  - name: smartmontools
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: mergerfs
  - name: snapper
  - name: sudo
  - name: gpg
#  - name: tailscale

# for an unpriv LXC add the following to lxc conf
# https://tailscale.com/kb/1130/lxc-unprivileged/
# 
# lxc.cgroup.devices.allow: c 10:200 rwm
# lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file
tailscale_exit_node: yes

# To route traffice for certain subnets through tailscale, add them here.
tailscale_advertise_routes: 
 - 10.147.17.0/24
 - 192.168.0.0/23


tailscale_accept_routes: no
tailscale_args: "--advertise-exit-node --advertise-routes=10.147.17.0/24,192.168.0.0/23 --hostname={{ hostname }}"
