---
- name: install snapd
  ansible.builtin.package:
    name: "snapd"

- name: Ensure snapd is running
  ansible.builtin.service:
    name: snapd
    state: started

- name: Create symbolic link
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: ansible_os_family == 'RedHat'
# Install a snap with classic confinement
- name: Install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    channel: "{{ item.channel | default('latest/stable') }}"
    classic: "{{ item.classic | default('false') }}"
    options: "{{ item.options | default('[]') }}"
    state: "{{ item.state | default('present') }}"
  loop: '{{ snap_packages }}'
